export enum ECity {
  MOSCOW = "Москва",
  SAINT_PETERSBURG = "Санкт-Петербург",
  NOVOSIBIRSK = "Новосибирск",
  YEKATERINBURG = "Екатеринбург",
  KAZAN = "Казань",
  NIZHNY_NOVGOROD = "Нижний Новгород",
  CHELYABINSK = "Челябинск",
  SAMARA = "Самара",
  OMSK = "Омск",
  ROSTOV = "Ростов-на-Дону",
  UFA = "Уфа",
  KRASNOYARSK = "Красноярск",
  VORONEZH = "Воронеж",
  PERM = "Пермь",
  VOLGOGRAD = "Волгоград",
  KRASNODAR = "Краснодар",
  SARATOV = "Саратов",
  TYUMEN = "Тюмень",
  TOLYATTI = "Тольятти",
  IZHEVSK = "Ижевск",
}
