export const developers = [
  {
    name: "Илья Непомнящий",
    role: "Team Lead / Fullstack Developer",
    avatar:
      "https://vk.com/doc664582531_696309706?hash=MO4yXjl98azsFIDZl7a7vnwVNNl5jfsZbknZ41bITog&dl=IfjQWX6sx6jM4wGUkJCURk4uNIzruPLDUZvOYolcs9X&api=1&no_preview=1",
    github: "https://github.com/duckpicker",
    contributions: ["Архитектура проекта", "Backend API", "DevOps"],
  },
  {
    name: "Александр Марков",
    role: "Assistant Team Lead/Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/17387318?v=4",
    github: "https://github.com/sashamarkov",
    contributions: ["UI компоненты", "Виджеты"],
  },
  {
    name: "Валерия Леонова",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/130294851?v=4",
    github: "https://github.com/lerachandi",
    contributions: ["UI компоненты", "Виджеты", "QA Manual", "Profile"],
  },
  {
    name: "Азат Зиганшин",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/211122835?v=4",
    github: "https://github.com/ZigaQuasar",
    contributions: ["UI компоненты", "Виджеты", "Регистрация/авторизация"],
  },
  {
    name: "Андрей Решетников",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/204704891?v=4",
    github: "https://github.com/ReshetnikovAV89",
    contributions: ["UI компоненты", "Виджеты", "Skill Cards"],
  },
  {
    name: "Эрик Авеян",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/202082401?v=4",
    github: "https://github.com/aveyanchoo",
    contributions: ["UI компоненты", "Виджеты", "Home Page"],
  },
  {
    name: "Мария Елисеева",
    role: "Middleware Developer",
    avatar: "https://avatars.githubusercontent.com/u/211976964?v=4",
    github: "https://github.com/Maria-Eliseeva",
    contributions: ["Api", "Утилиты"],
  },
  {
    name: "Вячеслав Кузнецов",
    role: "Middleware Developer",
    avatar: "https://avatars.githubusercontent.com/u/69216668?v=4",
    github: "https://github.com/vvk2020",
    contributions: ["Api", "Утилиты", "UI компоненты"],
  },
  {
    name: "Евгений Разорёнов",
    role: "Middleware Developer",
    avatar: "https://avatars.githubusercontent.com/u/59842963?v=4",
    github: "https://github.com/Dumpil-e",
    contributions: ["Api", "Утилиты", "UI компоненты"],
  },
  {
    name: "Полина Хафизова",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/113594915?v=4",
    github: "https://github.com/polinnett",
    contributions: ["UI компоненты", "Fix"],
  },
  {
    name: "Иван Алекс",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/211245629?v=4",
    github: "https://github.com/Tolpil",
    contributions: ["UI компоненты", "Виджеты"],
  },
  {
    name: "Вадим Кошенков",
    role: "Frontend Developer",
    avatar: "https://avatars.githubusercontent.com/u/189166741?v=4",
    github: "https://github.com/vadim-koshenkov",
    contributions: ["UI компоненты", "Fix", "Бонус за безумный трюк"],
  },
];
