FROM node:20-alpine AS builder
WORKDIR /app
COPY package*.json ./
RUN npm ci
COPY . .

ARG VITE_API_URL
ENV VITE_API_URL=${VITE_API_URL}
RUN npm run build

FROM alpine:latest AS production
WORKDIR /app
COPY --from=builder /app/dist ./dist

CMD ["sh", "-c", "cp -rf /app/dist/. /app/volume/ && sleep infinity"]
